<?php
/**
 * @file
 * badcamp_job_opportunitiies.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function badcamp_job_opportunitiies_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_job_opportunity_company'.
  $field_bases['field_job_opportunity_company'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_job_opportunity_company',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'direction' => 'DESC',
          'property' => 'title',
          'type' => 'property',
        ),
        'target_bundles' => array(
          'sponsor' => 'sponsor',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
