<?php
/**
 * @file
 * BADCamp Theme utility functions.
 */

/**
 * Implements hook_views_api().
 */
function badcamp_theme_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_views_view_block_grid(&$vars) {
  $view = $vars['view'];
  $rows = $vars['rows'];
  $style = $view->style_plugin;
  $options = $style->options;

  $sizes = array(
    'small' => NULL,
    'medium' => NULL,
    'large' => NULL,
  );
  $active_sizes = array_intersect_key(array_filter($options['grid']), $sizes);
  $block_grid_classes = array_map(function ($size, $cols) {
    return "{$size}-up-{$cols}";
  }, array_keys($active_sizes), $active_sizes);
  $vars['block_grid_class'] = implode(' ', $block_grid_classes);
  $vars['classes_array'] = array();
  $vars['classes'] = array();
  $default_row_class = isset($options['default_row_class']) ? $options['default_row_class'] : FALSE;
  $row_class_special = isset($options['row_class_special']) ? $options['row_class_special'] : FALSE;
  // Set up striping values.
  $count = 0;
  $max = count($rows);
  foreach ($rows as $id => $row) {
    $count++;
    if ($default_row_class) {
      $vars['classes'][$id][] = 'views-row';
      $vars['classes'][$id][] = 'views-row-' . $count;
    }
    if ($row_class_special) {
      $vars['classes'][$id][] = 'views-row-' . ($count % 2 ? 'odd' : 'even');
      if ($count == 1) {
        $vars['classes'][$id][] = 'views-row-first';
      }
      if ($count == $max) {
        $vars['classes'][$id][] = 'views-row-last';
      }
    }

    if ($row_class = $view->style_plugin->get_row_class($id)) {
      $vars['classes'][$id][] = $row_class;
    }

    // Flatten the classes to a string for each row for the template file.
    $vars['classes_array'][$id] = isset($vars['classes'][$id]) ? implode(' ', $vars['classes'][$id]) : '';
  }
}
